"""The interactive project dashboard (Streamlit).

Kept out of `src/cooling_twin` deliberately: `src/cooling_twin/viz/plots.py`
renders the STATIC figures that `reports/figures/` and the individual
`reports/0N_*.md` files embed, and stays that way. This package renders
one interactive page that recomputes against live BDG2 data and the run
artifacts; the two have different audiences, different runtimes (a report
figure is generated once by a script, this page is regenerated by
Streamlit on every widget interaction) and are kept as separate modules
so neither one's concerns leak into the other's.

Run with:

    streamlit run dashboard/app.py
"""
