"""Generate reports/01_data_quality.md from the real cleaning pipeline.

Run with:
    PYTHONPATH=src python3 -m scripts.generate_quality_report
(or however your Makefile's `report` target invokes it -- see
05_ENGINEERING_STANDARDS.md SS4)
"""

from __future__ import annotations

import logging
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import yaml

from cooling_twin.data.load import BDG2_ROOT, load_meter
from cooling_twin.data.quality import load_cleaning_config, run_cleaning_pipeline
from cooling_twin.data.weather import add_psychrometric_features, join_weather, load_weather

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

REPORT_PATH = Path("reports/01_data_quality.md")
FIGURE_PATH = Path("reports/figures/quality_before_after.png")


def _rule_summary_row(rule_name: str, log: pd.DataFrame, total_points: int) -> dict[str, object]:
    """Turn one rule's log into one row of the 04_DATA_CONTRACT SS4 table."""
    if rule_name == "C5_C6_gaps" and not log.empty:
        affected = int(log["length_hours"].sum())
    elif rule_name == "C8_change_points":
        affected = len(log)  # count of events, not hours
    elif rule_name == "C9_sparse_months" and not log.empty:
        affected = 0  # hours already counted via the gap log after nulling
    else:
        affected = int(log["length_hours"].sum()) if "length_hours" in log.columns else len(log)

    pct = 100 * affected / total_points if total_points else 0.0
    return {"rule": rule_name, "points_affected": affected, "pct_of_total": round(pct, 2)}


def generate_quality_report(
    raw_series_by_building: dict[str, tuple[pd.Series, pd.Series]],
    max_removed_pct: float = 15.0,
) -> None:
    """Run the full cleaning pipeline on every building and write the report.

    Args:
        raw_series_by_building: building_id -> (raw chilledwater_kwh
            series, raw rh_pct series), both post weather-join,
            pre-cleaning, sharing the same index.
        max_removed_pct: Threshold from config/cleaning.yaml
            (reporting.max_removed_pct). A building exceeding this is
            flagged in the report, per 06_ASSESSMENT.md's red flags.

    Raises:
        ValueError: If `raw_series_by_building` is empty.
    """
    if not raw_series_by_building:
        raise ValueError("no buildings provided")

    config = load_cleaning_config()
    lines: list[str] = ["# 01_data_quality.md — Data Quality Report\n"]
    lines.append("> Generated by `scripts/generate_quality_report.py`. Do not hand-edit.\n")

    cleaned_by_building: dict[str, pd.Series] = {}
    raw_by_building: dict[str, pd.Series] = {}
    flagged_buildings: list[str] = []

    for building_id, (raw, rh) in raw_series_by_building.items():
        cleaned, logs = run_cleaning_pipeline(raw, rh, config)
        cleaned_by_building[building_id] = cleaned
        raw_by_building[building_id] = raw

        total_points = len(raw)
        removed_pct = (
            100 * (cleaned.isna().sum() - raw.isna().sum()) / total_points
            if total_points
            else 0.0
        )

        lines.append(f"## {building_id}")
        lines.append(f"Total points: {total_points} | Removed by cleaning: {removed_pct:.2f}%")
        lines.append("")
        if removed_pct > max_removed_pct:
            flagged_buildings.append(building_id)
            lines.append(
                f"> **FLAGGED**: {removed_pct:.2f}% removed exceeds the "
                f"max_removed_pct threshold of {max_removed_pct}% -- see 06_ASSESSMENT.md."
            )
            lines.append("")

        lines.append("| Rule | Points Affected | % of Total |")
        lines.append("| --- | --- | --- |")
        for rule_name, log in logs.items():
            row = _rule_summary_row(rule_name, log, total_points)
            lines.append(f"| {row['rule']} | {row['points_affected']} | {row['pct_of_total']} |")
        lines.append("")

    _plot_before_after(raw_by_building, cleaned_by_building, FIGURE_PATH)
    lines.append("## Before / After")
    lines.append("")
    lines.append(f"![quality before/after]({FIGURE_PATH.as_posix()})")
    lines.append("")

    if flagged_buildings:
        lines.append(
            f"> {len(flagged_buildings)} building(s) exceeded the max_removed_pct "
            f"threshold: {', '.join(flagged_buildings)}"
        )
    else:
        lines.append("> No buildings exceeded the max_removed_pct threshold.")

    REPORT_PATH.write_text("\n".join(lines) + "\n")
    logger.info("Wrote %s", REPORT_PATH)


def _plot_before_after(
    raw_by_building: dict[str, pd.Series],
    cleaned_by_building: dict[str, pd.Series],
    out_path: Path,
) -> None:
    """One panel per building, raw vs cleaned overlaid, >= 150 DPI."""
    n = len(raw_by_building)
    fig, axes = plt.subplots(n, 1, figsize=(11, 3.2 * n), sharex=False)
    if n == 1:
        axes = [axes]

    for ax, building_id in zip(axes, raw_by_building, strict=True):
        raw = raw_by_building[building_id]
        cleaned = cleaned_by_building[building_id]
        ax.plot(raw.index, raw, color="0.75", linewidth=0.6, label="raw")
        ax.plot(cleaned.index, cleaned, color="C0", linewidth=0.6, label="cleaned")
        ax.set_title(building_id)
        ax.set_ylabel("chilled water (kWh)")
        ax.legend(loc="upper right", fontsize=8)

    plt.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def load_raw_series_with_weather() -> dict[str, tuple[pd.Series, pd.Series]]:
    """Read the selected buildings from config/buildings.yaml, then pull
    each one's raw chilledwater meter series AND its weather-joined
    rh_pct series -- both required by run_cleaning_pipeline()'s C1/C2/C7
    physical-bounds gate.

    config/buildings.yaml (written by select.py's write_buildings_yaml())
    already records each building's site_id, so no separate metadata.csv
    lookup is needed here -- join_weather() uses that site_id directly.

    Returns:
        building_id -> (raw chilledwater_kwh series, raw rh_pct series),
        both indexed by the same tz-naive hourly timestamp (BDG2's native
        local-time convention). Note: this is NOT yet a BuildingTimeSeries
        -- schema.py's tz-aware requirement and full contract are enforced
        later, at the L3.6 gate that consumes the *cleaned* output of this
        script, not the raw input to it.

    Raises:
        ValueError: If a selected building is missing from the meter data.
    """
    selection = yaml.safe_load(Path("config/buildings.yaml").read_text())
    entries = [entry for role_group in selection.values() for entry in role_group]

    meter_df = load_meter("chilledwater")
    weather_df = add_psychrometric_features(load_weather(BDG2_ROOT))

    available = set(meter_df["building_id"].unique())
    missing = [e["building_id"] for e in entries if e["building_id"] not in available]
    if missing:
        raise ValueError(f"buildings in config/buildings.yaml missing from meter data: {missing}")

    result: dict[str, tuple[pd.Series, pd.Series]] = {}
    for entry in entries:
        bid, site_id = entry["building_id"], entry["site_id"]
        building_meter = meter_df.loc[meter_df["building_id"] == bid]
        joined = join_weather(building_meter, weather_df, site_id).set_index("timestamp").sort_index()
        result[bid] = (
            joined["meter_reading"].rename(bid),
            joined["rh_pct"].rename(f"{bid}_rh"),
        )

    return result


if __name__ == "__main__":
    generate_quality_report(load_raw_series_with_weather())